"""empty message

Revision ID: aeaec9bc7d70
Revises: 8728959af44a
Create Date: 2023-10-21 19:48:46.064635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaec9bc7d70'
down_revision = '8728959af44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
