"""empty message

Revision ID: 8728959af44a
Revises: ac4e10cdfa50
Create Date: 2023-10-21 19:48:33.477929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8728959af44a'
down_revision = 'ac4e10cdfa50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
