"""empty message

Revision ID: ac4e10cdfa50
Revises: a037583a3dde
Create Date: 2023-10-21 19:48:29.184472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4e10cdfa50'
down_revision = 'a037583a3dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
