"""empty message

Revision ID: 5d1d309afc28
Revises: a8d371a3fadd
Create Date: 2023-10-21 18:18:21.073519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d1d309afc28'
down_revision = 'a8d371a3fadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_postulation', sa.Column('allowed_species', sa.Enum('dog', 'cat', name='species'), nullable=False))
    op.drop_column('care_postulation', 'name')
    op.drop_column('care_postulation', 'allowed_specie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_postulation', sa.Column('allowed_specie', postgresql.ENUM('dog', 'cat', name='species'), autoincrement=False, nullable=False))
    op.add_column('care_postulation', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('care_postulation', 'allowed_species')
    # ### end Alembic commands ###
